/*
 * Generated by Claude Sonnet 4.0
 * Test program that creates three threads in cascade
 * and tests the yield feature of the scheduler
 */

#include <stdio.h>
#include <uthread.h>

void thread3(void *arg)
{
    printf("thread3: start\n");
    uthread_yield();
    printf("thread3: end\n");
}

void thread2(void *arg)
{
    printf("thread2: start\n");
    uthread_create(thread3, NULL);
    uthread_yield();
    printf("thread2: end\n");
}

void thread1(void *arg)
{
    printf("thread1: start\n");
    uthread_create(thread2, NULL);
    uthread_yield();
    printf("thread1: end\n");
}

int main(void)
{
    int retval;
    
    printf("Starting uthread_yield test...\n");
    
    retval = uthread_run(false, thread1, NULL);
    
    if (retval) {
        printf("Error: uthread_run failed\n");
        return -1;
    }
    
    printf("uthread_yield test completed\n");
    return 0;
}